//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aquapark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientEntry
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsGoesInside { get; set; }
        public int IdEntryGate { get; set; }
        public int IdWristband { get; set; }
    
        public virtual EntryGate EntryGate { get; set; }
        public virtual Wristband Wristband { get; set; }
    }
}
