//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aquapark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryGate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntryGate()
        {
            this.ClientEntry = new HashSet<ClientEntry>();
        }
    
        public int Id { get; set; }
        public bool IsActive { get; set; }
        public int IdAttraction { get; set; }
    
        public virtual Attraction Attraction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientEntry> ClientEntry { get; set; }
    }
}
