//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aquapark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketInPriceList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketInPriceList()
        {
            this.ClientTicket = new HashSet<ClientTicket>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdTicketType { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> Entries { get; set; }
        public System.DateTime Duration { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int IdAttraction { get; set; }
    
        public virtual Attraction Attraction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientTicket> ClientTicket { get; set; }
        public virtual TicketType TicketType { get; set; }
    }
}
